package com.kan.ukapidemo.service.impl;

import com.kan.ukapidemo.service.UtilityService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class UtilityServiceImplTest {

  private static final String ALPHABETS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  private static final String CHARS = "ABCD";
  private static final String NUMBERS = "0123";
  private static final int SAMPLE_SIZE = 3;

  private static final List<String> PERMUTATIONS = List.of("AAA",
                                                           "AAB",
                                                           "AAC",
                                                           "AAD",
                                                           "ABA",
                                                           "ABB",
                                                           "ABC",
                                                           "ABD",
                                                           "ACA",
                                                           "ACB",
                                                           "ACC",
                                                           "ACD",
                                                           "ADA",
                                                           "ADB",
                                                           "ADC",
                                                           "ADD",
                                                           "BAA",
                                                           "BAB",
                                                           "BAC",
                                                           "BAD",
                                                           "BBA",
                                                           "BBB",
                                                           "BBC",
                                                           "BBD",
                                                           "BCA",
                                                           "BCB",
                                                           "BCC",
                                                           "BCD",
                                                           "BDA",
                                                           "BDB",
                                                           "BDC",
                                                           "BDD",
                                                           "CAA",
                                                           "CAB",
                                                           "CAC",
                                                           "CAD",
                                                           "CBA",
                                                           "CBB",
                                                           "CBC",
                                                           "CBD",
                                                           "CCA",
                                                           "CCB",
                                                           "CCC",
                                                           "CCD",
                                                           "CDA",
                                                           "CDB",
                                                           "CDC",
                                                           "CDD",
                                                           "DAA",
                                                           "DAB",
                                                           "DAC",
                                                           "DAD",
                                                           "DBA",
                                                           "DBB",
                                                           "DBC",
                                                           "DBD",
                                                           "DCA",
                                                           "DCB",
                                                           "DCC",
                                                           "DCD",
                                                           "DDA",
                                                           "DDB",
                                                           "DDC",
                                                           "DDD");

  private static final List<String> PERMUTATIONS_WITH_PREFIX = List.of("A000",
                                                                       "A001",
                                                                       "A002",
                                                                       "A003",
                                                                       "A010",
                                                                       "A011",
                                                                       "A012",
                                                                       "A013",
                                                                       "A020",
                                                                       "A021",
                                                                       "A022",
                                                                       "A023",
                                                                       "A030",
                                                                       "A031",
                                                                       "A032",
                                                                       "A033",
                                                                       "A100",
                                                                       "A101",
                                                                       "A102",
                                                                       "A103",
                                                                       "A110",
                                                                       "A111",
                                                                       "A112",
                                                                       "A113",
                                                                       "A120",
                                                                       "A121",
                                                                       "A122",
                                                                       "A123",
                                                                       "A130",
                                                                       "A131",
                                                                       "A132",
                                                                       "A133",
                                                                       "A200",
                                                                       "A201",
                                                                       "A202",
                                                                       "A203",
                                                                       "A210",
                                                                       "A211",
                                                                       "A212",
                                                                       "A213",
                                                                       "A220",
                                                                       "A221",
                                                                       "A222",
                                                                       "A223",
                                                                       "A230",
                                                                       "A231",
                                                                       "A232",
                                                                       "A233",
                                                                       "A300",
                                                                       "A301",
                                                                       "A302",
                                                                       "A303",
                                                                       "A310",
                                                                       "A311",
                                                                       "A312",
                                                                       "A313",
                                                                       "A320",
                                                                       "A321",
                                                                       "A322",
                                                                       "A323",
                                                                       "A330",
                                                                       "A331",
                                                                       "A332",
                                                                       "A333",
                                                                       "B000",
                                                                       "B001",
                                                                       "B002",
                                                                       "B003",
                                                                       "B010",
                                                                       "B011",
                                                                       "B012",
                                                                       "B013",
                                                                       "B020",
                                                                       "B021",
                                                                       "B022",
                                                                       "B023",
                                                                       "B030",
                                                                       "B031",
                                                                       "B032",
                                                                       "B033",
                                                                       "B100",
                                                                       "B101",
                                                                       "B102",
                                                                       "B103",
                                                                       "B110",
                                                                       "B111",
                                                                       "B112",
                                                                       "B113",
                                                                       "B120",
                                                                       "B121",
                                                                       "B122",
                                                                       "B123",
                                                                       "B130",
                                                                       "B131",
                                                                       "B132",
                                                                       "B133",
                                                                       "B200",
                                                                       "B201",
                                                                       "B202",
                                                                       "B203",
                                                                       "B210",
                                                                       "B211",
                                                                       "B212",
                                                                       "B213",
                                                                       "B220",
                                                                       "B221",
                                                                       "B222",
                                                                       "B223",
                                                                       "B230",
                                                                       "B231",
                                                                       "B232",
                                                                       "B233",
                                                                       "B300",
                                                                       "B301",
                                                                       "B302",
                                                                       "B303",
                                                                       "B310",
                                                                       "B311",
                                                                       "B312",
                                                                       "B313",
                                                                       "B320",
                                                                       "B321",
                                                                       "B322",
                                                                       "B323",
                                                                       "B330",
                                                                       "B331",
                                                                       "B332",
                                                                       "B333",
                                                                       "C000",
                                                                       "C001",
                                                                       "C002",
                                                                       "C003",
                                                                       "C010",
                                                                       "C011",
                                                                       "C012",
                                                                       "C013",
                                                                       "C020",
                                                                       "C021",
                                                                       "C022",
                                                                       "C023",
                                                                       "C030",
                                                                       "C031",
                                                                       "C032",
                                                                       "C033",
                                                                       "C100",
                                                                       "C101",
                                                                       "C102",
                                                                       "C103",
                                                                       "C110",
                                                                       "C111",
                                                                       "C112",
                                                                       "C113",
                                                                       "C120",
                                                                       "C121",
                                                                       "C122",
                                                                       "C123",
                                                                       "C130",
                                                                       "C131",
                                                                       "C132",
                                                                       "C133",
                                                                       "C200",
                                                                       "C201",
                                                                       "C202",
                                                                       "C203",
                                                                       "C210",
                                                                       "C211",
                                                                       "C212",
                                                                       "C213",
                                                                       "C220",
                                                                       "C221",
                                                                       "C222",
                                                                       "C223",
                                                                       "C230",
                                                                       "C231",
                                                                       "C232",
                                                                       "C233",
                                                                       "C300",
                                                                       "C301",
                                                                       "C302",
                                                                       "C303",
                                                                       "C310",
                                                                       "C311",
                                                                       "C312",
                                                                       "C313",
                                                                       "C320",
                                                                       "C321",
                                                                       "C322",
                                                                       "C323",
                                                                       "C330",
                                                                       "C331",
                                                                       "C332",
                                                                       "C333",
                                                                       "D000",
                                                                       "D001",
                                                                       "D002",
                                                                       "D003",
                                                                       "D010",
                                                                       "D011",
                                                                       "D012",
                                                                       "D013",
                                                                       "D020",
                                                                       "D021",
                                                                       "D022",
                                                                       "D023",
                                                                       "D030",
                                                                       "D031",
                                                                       "D032",
                                                                       "D033",
                                                                       "D100",
                                                                       "D101",
                                                                       "D102",
                                                                       "D103",
                                                                       "D110",
                                                                       "D111",
                                                                       "D112",
                                                                       "D113",
                                                                       "D120",
                                                                       "D121",
                                                                       "D122",
                                                                       "D123",
                                                                       "D130",
                                                                       "D131",
                                                                       "D132",
                                                                       "D133",
                                                                       "D200",
                                                                       "D201",
                                                                       "D202",
                                                                       "D203",
                                                                       "D210",
                                                                       "D211",
                                                                       "D212",
                                                                       "D213",
                                                                       "D220",
                                                                       "D221",
                                                                       "D222",
                                                                       "D223",
                                                                       "D230",
                                                                       "D231",
                                                                       "D232",
                                                                       "D233",
                                                                       "D300",
                                                                       "D301",
                                                                       "D302",
                                                                       "D303",
                                                                       "D310",
                                                                       "D311",
                                                                       "D312",
                                                                       "D313",
                                                                       "D320",
                                                                       "D321",
                                                                       "D322",
                                                                       "D323",
                                                                       "D330",
                                                                       "D331",
                                                                       "D332",
                                                                       "D333");

  private UtilityService utilityService;

  @BeforeEach
  void setUp() {
    utilityService = new UtilityServiceImpl();
  }

  @Test
  void getNthPermutationWithRepetition() {
    for (int i = 0; i < PERMUTATIONS.size(); i++) {
      String actual = utilityService.getNthPermutationWithRepetition(i+1, CHARS, SAMPLE_SIZE);
      assertEquals(PERMUTATIONS.get(i), actual);
    }
  }

  @Test
  void getNthPermutationWithRepetition_withAllAlphabets() {
    String actual = utilityService.getNthPermutationWithRepetition(30, ALPHABETS, 6);
    assertEquals("AAAABD", actual);
  }

  @Test
  void getNthPermutationWithRepetitionAndPrefix() {
    for (int i = 0; i < PERMUTATIONS_WITH_PREFIX.size(); i++) {
      String actual = utilityService.getNthPermutationWithRepetitionAndPrefix(i+1, CHARS, NUMBERS, 4);
//      System.out.println(actual);
      assertEquals(PERMUTATIONS_WITH_PREFIX.get(i), actual);
    }
  }

//  @Test
  void getPermutationsWithRepetitionAndPrefix() {
    List<String> actual = utilityService.getPermutationsWithRepetitionAndPrefix(CHARS, NUMBERS, 3);
    assertNotNull(actual);
  }
}